
# config prolile here. e.g.: "dev"、"online"
profile = "dev"

# config the policy here.
# policy.path       e.g.:"usdt eth btc"
# policy.permutation     all     all permutation the path and start as the first one in policy.path
# policy.permutation     none    strict compliance the path
[policy]
    path = "usdt eth btc eos usdt"
    permutation = ""

place_account_id = "kook002"

[order]
    account-id = "kook002"
    amount = 10
    price = 10000
    source = "api"
    symbol = "btcusdt"
    type = "buy-limit"
    stop-price = 3000
    operator = "gte"

